/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ROBOTR = 5;
  /** RegularExpression Id. */
  int VARS = 6;
  /** RegularExpression Id. */
  int PROCS = 7;
  /** RegularExpression Id. */
  int LEFT = 8;
  /** RegularExpression Id. */
  int AROUND = 9;
  /** RegularExpression Id. */
  int FRONT = 10;
  /** RegularExpression Id. */
  int BACK = 11;
  /** RegularExpression Id. */
  int NORTH = 12;
  /** RegularExpression Id. */
  int SOUTH = 13;
  /** RegularExpression Id. */
  int WEST = 14;
  /** RegularExpression Id. */
  int EAST = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int FACING = 22;
  /** RegularExpression Id. */
  int CANPUT = 23;
  /** RegularExpression Id. */
  int CANPICK = 24;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 25;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 26;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 27;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int MOV = 30;
  /** RegularExpression Id. */
  int RIGHT = 31;
  /** RegularExpression Id. */
  int PUT = 32;
  /** RegularExpression Id. */
  int PICK = 33;
  /** RegularExpression Id. */
  int POP = 34;
  /** RegularExpression Id. */
  int GO = 35;
  /** RegularExpression Id. */
  int HOP = 36;
  /** RegularExpression Id. */
  int ASSIGNTO = 37;
  /** RegularExpression Id. */
  int GOTO = 38;
  /** RegularExpression Id. */
  int MOVE = 39;
  /** RegularExpression Id. */
  int TURN = 40;
  /** RegularExpression Id. */
  int FACE = 41;
  /** RegularExpression Id. */
  int MOVETOTHE = 42;
  /** RegularExpression Id. */
  int MOVEINDIR = 43;
  /** RegularExpression Id. */
  int JUMPTOTHE = 44;
  /** RegularExpression Id. */
  int JUMPINDIR = 45;
  /** RegularExpression Id. */
  int NOP = 46;
  /** RegularExpression Id. */
  int BALLOONS = 47;
  /** RegularExpression Id. */
  int CHIPS = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int COLON = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int LBRACKET = 52;
  /** RegularExpression Id. */
  int RBRACKET = 53;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 54;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 55;
  /** RegularExpression Id. */
  int LPARENTHESIS = 56;
  /** RegularExpression Id. */
  int RPARENTHESIS = 57;
  /** RegularExpression Id. */
  int BAR = 58;
  /** RegularExpression Id. */
  int NUMBER = 59;
  /** RegularExpression Id. */
  int STRING = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"left\"",
    "\"around\"",
    "\"front\"",
    "\"back\"",
    "\"north\"",
    "\"south\"",
    "\"west\"",
    "\"east\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "\"Mov\"",
    "\"right\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"Go\"",
    "\"Hop\"",
    "\"assignTo\"",
    "\"goTo\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "<NUMBER>",
    "<STRING>",
  };

}
