/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ROBOTR = 5;
  /** RegularExpression Id. */
  int VARS = 6;
  /** RegularExpression Id. */
  int PROCS = 7;
  /** RegularExpression Id. */
  int ASSIGNTO = 8;
  /** RegularExpression Id. */
  int GOTO = 9;
  /** RegularExpression Id. */
  int MOVE = 10;
  /** RegularExpression Id. */
  int TURN = 11;
  /** RegularExpression Id. */
  int FACE = 12;
  /** RegularExpression Id. */
  int MOVETOTHE = 13;
  /** RegularExpression Id. */
  int MOVEINDIR = 14;
  /** RegularExpression Id. */
  int JUMPTOTHE = 15;
  /** RegularExpression Id. */
  int JUMPINDIR = 16;
  /** RegularExpression Id. */
  int NOP = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int REPEAT = 23;
  /** RegularExpression Id. */
  int FACING = 24;
  /** RegularExpression Id. */
  int CANPUT = 25;
  /** RegularExpression Id. */
  int CANPICK = 26;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 27;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 28;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 29;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int LEFT = 32;
  /** RegularExpression Id. */
  int AROUND = 33;
  /** RegularExpression Id. */
  int FRONT = 34;
  /** RegularExpression Id. */
  int BACK = 35;
  /** RegularExpression Id. */
  int NORTH = 36;
  /** RegularExpression Id. */
  int SOUTH = 37;
  /** RegularExpression Id. */
  int WEST = 38;
  /** RegularExpression Id. */
  int EAST = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int COLON = 41;
  /** RegularExpression Id. */
  int SEMICOLON = 42;
  /** RegularExpression Id. */
  int LBRACKET = 43;
  /** RegularExpression Id. */
  int RBRACKET = 44;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 45;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 46;
  /** RegularExpression Id. */
  int LPARENTHESIS = 47;
  /** RegularExpression Id. */
  int RPARENTHESIS = 48;
  /** RegularExpression Id. */
  int BAR = 49;
  /** RegularExpression Id. */
  int MOV = 50;
  /** RegularExpression Id. */
  int RIGHT = 51;
  /** RegularExpression Id. */
  int PUT = 52;
  /** RegularExpression Id. */
  int PICK = 53;
  /** RegularExpression Id. */
  int POP = 54;
  /** RegularExpression Id. */
  int GO = 55;
  /** RegularExpression Id. */
  int HOP = 56;
  /** RegularExpression Id. */
  int BALLOONS = 57;
  /** RegularExpression Id. */
  int CHIPS = 58;
  /** RegularExpression Id. */
  int NUMBER = 59;
  /** RegularExpression Id. */
  int STRING = 60;
  /** RegularExpression Id. */
  int NUM = 61;
  /** RegularExpression Id. */
  int DIGIT = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"assignTo\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canput\"",
    "\"canpick\"",
    "\"canmoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "\"left\"",
    "\"around\"",
    "\"front\"",
    "\"back\"",
    "\"north\"",
    "\"south\"",
    "\"west\"",
    "\"east\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMBER>",
    "<STRING>",
    "<NUM>",
    "<DIGIT>",
  };

}
